# Generated by Django 6.0.3 on 2026-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(choices=[('MTH', 'Math'), ('SCI', 'Science'), ('SPC', 'Speech'), ('WRI', 'Writing'), ('ACC', 'Accounting'), ('CIS', 'Computer Science'), ('LAN', 'Language'), ('ACD', 'Academic Coach'), ('MTC', 'Math Coach'), ('AEA', 'AEA - Academic Coach')], max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='subject',
        ),
        migrations.AddField(
            model_name='employee',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='employees', to='account.subject'),
        ),
    ]
