# Generated by Django 6.0.3 on 2026-04-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_operatinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
