# Generated by Django 6.0.3 on 2026-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_department_remove_employee_department_and_more'),
        ('scheduling', '0008_remove_scheduleentry_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='subjects',
        ),
        migrations.AddField(
            model_name='employee',
            name='part_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('TUTOR', 'Tutor'), ('ARC_ASSISTANT', 'ARC Assistant'), ('ADMIN', 'Admin')], default='TUTOR'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
