# Generated by Django 6.0.3 on 2026-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_employee_departments_remove_employee_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ASSISTANT_I', 'Assistant I'), ('ASSISTANT_II', 'Assistant II'), ('TUTOR', 'Tutor')], default='TUTOR', max_length=20),
        ),
    ]
