# Generated by Django 6.0.3 on 2026-07-07 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_employee_desired_weekly_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='desired_weekly_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
