# Generated by Django 6.0.3 on 2026-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_employee_desired_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availability_override_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
