# Generated by Django 6.0.3 on 2026-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_employee_availability_override_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_password', models.CharField(default='Test123!', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ASSISTANT_I', 'Assistant I'), ('ASSISTANT_II', 'Assistant II'), ('TUTOR', 'Tutor'), ('LIBRARY', 'Library Staff')], default='TUTOR', max_length=20),
        ),
    ]
