# Generated by Django 6.0.3 on 2026-04-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatinghours',
            options={'verbose_name_plural': 'Operating Hours'},
        ),
    ]
