# Generated by Django 6.0.3 on 2026-04-22 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_department_remove_employee_department_and_more'),
        ('scheduling', '0002_alter_operatinghours_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatinghours',
            options={'ordering': [models.Case(models.When(day_of_week='MON', then=models.Value(0)), models.When(day_of_week='TUE', then=models.Value(1)), models.When(day_of_week='WED', then=models.Value(2)), models.When(day_of_week='THU', then=models.Value(3)), models.When(day_of_week='FRI', then=models.Value(4)), output_field=models.IntegerField())], 'verbose_name_plural': 'Operating Hours'},
        ),
        migrations.AlterModelOptions(
            name='weeklyavailability',
            options={'ordering': [models.Case(models.When(day_of_week='MON', then=models.Value(0)), models.When(day_of_week='TUE', then=models.Value(1)), models.When(day_of_week='WED', then=models.Value(2)), models.When(day_of_week='THU', then=models.Value(3)), models.When(day_of_week='FRI', then=models.Value(4)), output_field=models.IntegerField()), 'start_time'], 'verbose_name_plural': 'Weekly Availabilities'},
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_blocks', to='account.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.Case(models.When(day_of_week='MON', then=models.Value(0)), models.When(day_of_week='TUE', then=models.Value(1)), models.When(day_of_week='WED', then=models.Value(2)), models.When(day_of_week='THU', then=models.Value(3)), models.When(day_of_week='FRI', then=models.Value(4)), output_field=models.IntegerField()), 'start_time'],
            },
        ),
    ]
