# Generated by Django 6.0.3 on 2026-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_dateoperatinghours_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
