# Generated by Django 6.0.3 on 2026-05-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_department_remove_employee_department_and_more'),
        ('scheduling', '0005_add_schedule_entry_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locations', models.CharField(blank=True, default='', help_text='Comma-separated sub-column labels, e.g. Drop-in,Coach. Leave blank for no sub-columns.', max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='account.department')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='scheduling.subject'),
        ),
    ]
