# Generated by Django 6.0.3 on 2026-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_add_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='account_subject_code',
            field=models.CharField(blank=True, default='', help_text='account.Subject code to filter which employees appear (e.g. MTH, SCI, CIS).', max_length=3),
        ),
    ]
