# Generated by Django 6.0.3 on 2026-06-12 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_add_account_subject_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='department',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='department',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='member_of', to=settings.AUTH_USER_MODEL)),
                ('schedulers', models.ManyToManyField(blank=True, related_name='scheduler_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='scheduling.schedule'),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_blocks', to='scheduling.schedule'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
