# Generated by Django 6.0.3 on 2026-06-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_remove_scheduleentry_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='scheduling.schedule'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_blocks', to='scheduling.schedule'),
        ),
    ]
