# Generated by Django 6.0.3 on 2026-06-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_scheduleentry_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(default='#003F7F', max_length=7),
        ),
    ]
