# Generated by Django 6.0.3 on 2026-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_shift_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='custom_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
