# Generated by Django 6.0.3 on 2026-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_weeklyschedule_custom_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('opens_at', models.DateField(blank=True, null=True)),
                ('closes_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Availability Window',
            },
        ),
    ]
