# Generated by Django 6.0.3 on 2026-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_availabilitywindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='custom_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='custom_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
